# Generated by Django 5.1.1 on 2024-11-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_business1_freelancer_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
