# Generated by Django 5.1.1 on 2024-11-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_project_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
