# Generated by Django 5.1.1 on 2024-11-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_delete_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
