# Generated by Django 5.1.1 on 2024-11-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_proposedproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timeline', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stipend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.business1')),
            ],
        ),
    ]
