# Generated by Django 5.1.1 on 2024-11-01 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_business1_user_name_freelancer_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedproject',
            name='freelancer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.freelancer'),
            preserve_default=False,
        ),
    ]
