# Generated by Django 5.1.1 on 2024-11-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_assignedproject_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedproject',
            name='status',
        ),
        migrations.AddField(
            model_name='assignedproject',
            name='Inprogress',
            field=models.BooleanField(default=True),
        ),
    ]
