# Generated by Django 5.1.1 on 2024-11-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_delete_project'),
        ('homepage', '0009_remove_assignedproject_status_and_more'),
    ]

    operations = [
    ]
