# Generated by Django 5.1.1 on 2024-11-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business1',
            name='photo',
            field=models.ImageField(default='default-profile.png', upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='photo',
            field=models.ImageField(default='default-profile.png', upload_to='profile_photos/'),
        ),
    ]
