# Generated by Django 5.1.1 on 2024-11-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_business1_photo_freelancer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business1',
            name='photo',
            field=models.ImageField(default='images.jpeg', upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='photo',
            field=models.ImageField(default='images.jpeg', upload_to='profile_photos/'),
        ),
    ]
