# Generated by Django 5.1.1 on 2024-11-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_rename_freelancer_ratingsystem_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingsystem',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
