from django.contrib import admin

from .models import Business1,Freelancer,UserProfile,AssignedProject,ProposedProject,ratingsystem,Project # Replace with the actual class name generated by inspectdb

admin.site.register(Business1)
admin.site.register(Project)

admin.site.register(ProposedProject)
admin.site.register(AssignedProject)
admin.site.register(Freelancer)
admin.site.register(UserProfile)
admin.site.register(ratingsystem)