from django.contrib import admin

from .models import Business1,Freelancer,UserProfile,AssignedProject,ProposedProject  # Replace with the actual class name generated by inspectdb

admin.site.register(Business1)

admin.site.register(ProposedProject)
admin.site.register(AssignedProject)
admin.site.register(Freelancer)
admin.site.register(UserProfile)